version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./initialSql:/data
      - ./clientTheme:/app/wp-content/themes/clientTheme
      - ./plugins:/app/wp-content/plugins
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      THEMES: >-
        [local]clientTheme
    container_name: wpcontainer
        
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: dbcontainer
volumes:
  data:
